"""
Scheduler Agent
An independent LangGraph-based agent that schedules interviews between
candidates and recruiters.

Supports two calendar authentication modes:
  - OAuth token (preferred): recruiter authenticates via browser popup
  - Service account (fallback): uses service_account.json

Workflow:
  validate_input → find_slot → generate_link → create_event → send_email
"""

import traceback
import logging
from datetime import datetime, timedelta
from typing import TypedDict, Optional

from langgraph.graph import StateGraph, END

from utils.slot_generator import find_available_slot, SLOT_DURATION_MINUTES
from utils.calendar_service import (
    get_calendar_service,
    get_calendar_service_from_token,
    get_busy_slots,
    create_calendar_event,
)
from utils.meeting_link_service import generate_meeting_link  # kept for fallback
from utils.scheduler_email_service import send_interview_email

logger = logging.getLogger("scheduler_agent")


# ── State definition ───────────────────────────────────────────────────

class SchedulerState(TypedDict):
    candidate_name: str
    candidate_email: str
    job_role: str
    recruiter_name: str
    recruiter_email: str
    calendar_access_token: Optional[str]  # OAuth token from frontend
    # Workflow outputs
    scheduled_time: Optional[str]         # ISO-format string once resolved
    meeting_link: Optional[str]
    invite_id: Optional[str]  # ID to track replies (e.g., INV-12345)
    calendar_event_id: str
    email_sent: bool
    error: Optional[str]


# ── Helper: get calendar service based on available auth ───────────────

def _get_service(state: SchedulerState):
    """Return a Calendar API service using OAuth token if available,
    otherwise fall back to service account."""
    token = state.get("calendar_access_token")
    if token:
        logger.info("Using OAuth user token for calendar access.")
        return get_calendar_service_from_token(token)
    else:
        logger.info("No OAuth token — falling back to service account.")
        return get_calendar_service()


# ── Node functions ─────────────────────────────────────────────────────

def validate_input(state: SchedulerState) -> dict:
    """Ensure all required fields are present and non-empty."""
    logger.info("--- SCHEDULER: VALIDATE INPUT ---")
    required = [
        "candidate_name",
        "candidate_email",
        "job_role",
        "recruiter_name",
        "recruiter_email",
    ]
    missing = [f for f in required if not state.get(f)]
    if missing:
        return {"error": f"Missing required fields: {', '.join(missing)}"}

    # Prevent using the service account email as the recruiter email
    recruiter_email = state["recruiter_email"].strip().lower()
    if "iam.gserviceaccount.com" in recruiter_email:
        return {
            "error": "The recruiter email must be a personal Google account "
                     "(e.g. name@gmail.com), not a service account email."
        }

    logger.info(f"Validated — recruiter calendar: {state['recruiter_email']}")
    return {}


def find_slot(state: SchedulerState) -> dict:
    """Retrieve busy slots from the recruiter's calendar and pick a free one."""
    logger.info("--- SCHEDULER: FIND SLOT ---")
    if state.get("error"):
        return {}

    try:
        service = _get_service(state)
        # With OAuth, use "primary" calendar; with service account use recruiter email
        calendar_id = "primary" if state.get("calendar_access_token") else state["recruiter_email"]
        # Use IST since Docker runs in UTC but working hours are IST
        from utils.slot_generator import IST
        today = datetime.now(IST).replace(tzinfo=None)

        # Gather busy slots for the next 30 working days
        all_busy = []
        check_date = today
        for _ in range(30):
            try:
                day_busy = get_busy_slots(service, calendar_id, check_date)
                all_busy.extend(day_busy)
            except Exception:
                pass  # if a single day query fails, continue
            check_date += timedelta(days=1)

        slot = find_available_slot(today, all_busy)
        if slot is None:
            return {"error": "No available interview slots in the next 30 working days."}

        return {"scheduled_time": slot.strftime("%Y-%m-%d %H:%M")}

    except Exception as e:
        logger.error(f"Calendar API error: {e}")
        traceback.print_exc()
        return {"error": f"Failed to access recruiter calendar: {str(e)}"}


def generate_link(state: SchedulerState) -> dict:
    """Set a placeholder meeting link — the real Google Meet link is
    generated by the Calendar API in the create_event step."""
    logger.info("--- SCHEDULER: GENERATE LINK ---")
    if state.get("error"):
        return {}

    # Placeholder; will be overridden by real Meet link from create_event
    return {"meeting_link": "pending"}


def create_event(state: SchedulerState) -> dict:
    """Insert the interview into the recruiter's Google Calendar.
    Non-fatal: logs a warning and continues if the calendar API fails."""
    logger.info("--- SCHEDULER: CREATE EVENT ---")
    if state.get("error"):
        return {}

    try:
        service = _get_service(state)
        calendar_id = "primary" if state.get("calendar_access_token") else state["recruiter_email"]
        
        # Generate invite_id if not present
        invite_id = state.get("invite_id")
        if not invite_id:
            import random
            invite_id = f"INV-{random.randint(10000, 99999)}"

        start_dt = datetime.strptime(state["scheduled_time"], "%Y-%m-%d %H:%M")
        end_dt   = start_dt + timedelta(minutes=SLOT_DURATION_MINUTES)

        summary     = f"Interview – {state['job_role']} ({state['candidate_name']}) [{invite_id}]"
        description = (
            f"Candidate : {state['candidate_name']}\n"
            f"Email     : {state['candidate_email']}\n"
            f"Role      : {state['job_role']}\n"
            f"Meeting   : {state['meeting_link']}"
        )

        event_result = create_calendar_event(
            service=service,
            calendar_id=calendar_id,
            summary=summary,
            description=description,
            start_dt=start_dt,
            end_dt=end_dt,
            meeting_link=state["meeting_link"],
        )
        updates = {"calendar_event_id": event_result["event_id"], "invite_id": invite_id}
        # Override with the real Google Meet link if available
        if event_result.get("meet_link"):
            updates["meeting_link"] = event_result["meet_link"]
        return updates

    except Exception as e:
        logger.warning(
            f"Calendar event creation failed (non-fatal): {e}. "
        )
        return {"calendar_event_id": "unavailable"}


def send_email(state: SchedulerState) -> dict:
    """Email the candidate with interview details.
    Non-fatal: logs a warning and continues if SMTP fails."""
    logger.info("--- SCHEDULER: SEND EMAIL ---")
    if state.get("error"):
        return {}
        
    try:
        # generate invite id if skipped
        invite_id = state.get("invite_id")
        if not invite_id:
            import random
            invite_id = f"INV-{random.randint(10000, 99999)}"

        interview_dt = datetime.strptime(state["scheduled_time"], "%Y-%m-%d %H:%M")

        success = send_interview_email(
            candidate_name=state["candidate_name"],
            candidate_email=state["candidate_email"],
            job_role=state["job_role"],
            interview_datetime=interview_dt,
            meeting_link=state["meeting_link"],
            recruiter_name=state["recruiter_name"],
            recruiter_email=state["recruiter_email"],
            invite_id=invite_id
        )
        return {"email_sent": success}

    except Exception as e:
        logger.warning(f"Email sending failed (non-fatal): {e}")
        return {"email_sent": False}


# ── Conditional edge helper ────────────────────────────────────────────

def check_error(state: SchedulerState) -> str:
    """Route to END early if any node set an error."""
    return "end" if state.get("error") else "continue"


# ── Build the graph ────────────────────────────────────────────────────

workflow = StateGraph(SchedulerState)

workflow.add_node("validate_input", validate_input)
workflow.add_node("find_slot", find_slot)
workflow.add_node("generate_link", generate_link)
workflow.add_node("create_event", create_event)
workflow.add_node("send_email", send_email)

workflow.set_entry_point("validate_input")

# After each node, check for errors before proceeding
workflow.add_conditional_edges("validate_input", check_error, {"continue": "find_slot", "end": END})
workflow.add_conditional_edges("find_slot", check_error, {"continue": "generate_link", "end": END})
workflow.add_conditional_edges("generate_link", check_error, {"continue": "create_event", "end": END})
workflow.add_conditional_edges("create_event", check_error, {"continue": "send_email", "end": END})
workflow.add_edge("send_email", END)

app = workflow.compile()


# ── Public entry-point ─────────────────────────────────────────────────

async def run_scheduler_agent(input_data: dict) -> dict:
    """
    Invoke the scheduler agent with candidate / recruiter details.

    Parameters
    ----------
    input_data : dict
        Must contain: candidate_name, candidate_email, job_role,
        recruiter_name, recruiter_email.
        Optional: calendar_access_token (OAuth token from frontend).

    Returns
    -------
    dict
        On success / failure with status key.
    """
    state: SchedulerState = {
        "candidate_name": input_data.get("candidate_name", ""),
        "candidate_email": input_data.get("candidate_email", ""),
        "job_role": input_data.get("job_role", ""),
        "recruiter_name": input_data.get("recruiter_name", ""),
        "recruiter_email": input_data.get("recruiter_email", ""),
        "calendar_access_token": input_data.get("calendar_access_token"),
        "scheduled_time": None,
        "meeting_link": "",
        "calendar_event_id": "",
        "email_sent": False,
        "error": None,
    }

    try:
        result = await app.ainvoke(state)

        if result.get("error"):
            return {"status": "Failed", "error": result["error"]}

        return {
            "status": "Success",
            "candidate_name": result["candidate_name"],
            "scheduled_time": result["scheduled_time"],
            "meeting_link": result["meeting_link"],
            "calendar_event_id": result["calendar_event_id"],
            "email_sent": result["email_sent"],
        }

    except Exception as e:
        logger.error(f"Scheduler Agent failed: {e}")
        traceback.print_exc()
        return {"status": "Failed", "error": f"Agent encountered an error: {str(e)}"}
